### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by wilbertom** [nikhilm/uvbook#44]
I'm so sorry if I'm making a noob mistake. However I think the error handling section is wrong. 

While reading the book I tried:

```
#include <stdio.h>
#include <uv.h>

int main()
{
    uv_loop_t *loop = uv_loop_new();

    printf("Now quitting...\n");

    uv_run(loop, UV_RUN_DEFAULT);
    printf("Error: %s\n", uv_err_name(uv_last_error(loop)));

    return 0;

}
```

I didn't expect this to work since I'm not really doing anything yet, but the error I got wasn't the type I expected:

```
gcc -g -Wall  -o uvbook uvbook.c /usr/local/lib/libuv.a -lrt -ldl -lm -pthread -lcurl
uvbook.c: In function ‘main’:
uvbook.c:11:5: warning: implicit declaration of function ‘uv_last_error’ [-Wimplicit-function-declaration]
/tmp/ccSoDWZT.o: In function `main':
/home/wil/Programming/Edu/uv/uvbook.c:11: undefined reference to `uv_last_error'
collect2: ld returned 1 exit status
make: *** [all] Error 1

```

So before opening a Github issue I decided to do some research. I looked at `libuv`'s `include/uv.h` file to see if I was just doing something wrong. I found that uv_strerror and uv_err_name take `int`s as parameters and not `uv_err_t`:

```
/*
* Most functions return 0 on success or an error code < 0 on failure.
*/
UV_EXTERN const char* uv_strerror(int err);
UV_EXTERN const char* uv_err_name(int err);
```

I checked to see when this changed and when the book was last updated. It turns out the last commit 16b671fa7475ae1650fc1c35aecae6af6f8a4dbc added the error handling(1 month ago) to fix #43, but `libuv` [changed](https://github.com/joyent/libuv/commit/3ee4d3f183331a123ce35edd0d32268a2bb22aa5) about 9 months.

If I'm correct I can update the book. If I'm not then I'm sorry for wasting your time.

**Comment by nikhilm** [comment]
Closing this as examples have been fixed and book is being fixed.
