### ISSUE TITLE
memory leaks in sample codes

### ISSUE THREAD

**Issue by azadkuh** [nikhilm/uvbook#53]
the examples in the book are great to learn, easy and clean and I understand that they may have been trimmed for simplicity.

but It's better to warn learners about memory leaks in the examples:
for instance [tcp-echo-server](https://github.com/nikhilm/uvbook/blob/master/code/tcp-echo-server/main.c) leaks at:
* `main.c(23)`: if the connections drops the allocated buffer at `main.c(9)` must be freed by user.
* `main.c(41)`: the `uv_tcp_t *client = (uv_tcp_t*) malloc(sizeof(uv_tcp_t))` must be freed by user.

after a few hundred connections to this sample code, `valgrind` reports a huge amount of memory leak.

> it would be nice to introduce a new section in the book for this topic as double closing handles, closing states, memory leaks, ... are common questions about libuv.

**Comment by nikhilm** [comment]
Since libuv now has documentation, I think it is better to have the canonical sources document details like closing handles.

**Comment by shyba** [comment]
Hi, your book is awesome and I am learning a lot, but had a hard time figuring out memory leaks in this chapter with valgrind (I am still learning C as well).
IMHO, it would be awesome to have at least a line saying that memory leaks are expected and out of scope for this chapter.
Thank you a lot for writing it.

**Comment by nikhilm** [comment]
I've added a note at the beginning. http://nikhilm.github.io/uvbook/networking.html
