### ISSUE TITLE
uv_tcp_connect with wrong arguments in networking.rst?

### ISSUE THREAD

**Issue by gregkalapos** [nikhilm/uvbook#61]
Hi, just a small thing:

in networking.rst shouldn't this line in the "Client" section
```c
uv_tcp_connect(connect, socket, dest, on_connect);
```
rather look like this (missing cast...?):
```c
uv_tcp_connect(connect, socket, (const struct sockaddr*)&dest, on_connect);
```
?

Cheers,
Greg

**Comment by nikhilm** [comment]
Hi Greg,

You are right. I updated the code examples but missed the in line code that doesn't get compiled.
