### ISSUE TITLE
uvbook/code/progress/main.c undefined behavior

### ISSUE THREAD

**Issue by dirkson** [nikhilm/uvbook#65]
Heyo!

In uvbook/code/progress/main.c, after line 17's uv_async_send, I believe there is a chance that the main thread could reach line 23 before the uv_async_send callback function completes. If this happens, then line 13's "percentage" variable falls out of scope, leaving uv_async_send with a pointer to a part of the stack that could be rapidly overwritten.

The "sleep 1" on line 19 likely masks this issue, so that it doesn't crop up in most runs of this particular program. But I suspect people implementing real-world equivalents based on this example would rapidly run into the issue.

Cheers!

**Comment by nikhilm** [comment]
You are right. How about I just make `percentage` global, exercising my right to "examples that don't echo real world best practices"?

**Comment by dirkson** [comment]
Sounds fine to me : )

Another way to do it, albeit not quite as easy, would be to assign the async data pointer just after init, never change the pointer, do something similar to line 31 each time you wanted to change the value the pointer is pointing to. That's roughly the approach I take.
