### ISSUE TITLE
No matching function for call to 'uv_tcp_connect'

### ISSUE THREAD

**Issue by kelvin7feng** [nikhilm/uvbook#68]
I have added "Header Search Paths" to project at Xcode. However, it give me this tips. What should I do ?

**Comment by nikhilm** [comment]
I'm away from a computer till August 18th. 

Nikhil
--
Sent from a tiny keyboard.

		_____________________________

**Comment by nikhilm** [comment]
@kelvin7feng I was not able to reproduce this on a Mac when running `make` in the `code/` directory.
