### ISSUE TITLE
why cant i free the handle by this way?

### ISSUE THREAD

**Issue by peze** [nikhilm/uvbook#75]
in  the tcp-echo-server example，i find this code in the on_new_connection function

`uv_tcp_t *client = (uv_tcp_t*) malloc(sizeof(uv_tcp_t));`

but i never find where the client are freed,so i want to free it in the function free_write_req like this

	void echo_write(uv_write_t *req, int status) {
	    if (status) {
	        fprintf(stderr, "Write error %s\n", uv_strerror(status));
	    }
	    free(req->handle);
	    free_write_req(req);
	}

however, it will make core dumped....i am very puzzle about that , if i don't free the client won't cause the program memory overflow

**Comment by bnoordhuis** [comment]
You need to `uv_close()` the handle first, wait for it to close (by means of the callback), and only then can you free its memory.  The `req` can be freed immediately though.
