### ISSUE TITLE
Github pages for the book not found (404)

### ISSUE THREAD

**Issue by mihaiolteanu** [nikhilm/uvbook#85]
https://nikhilm.github.com/uvbook

![Mar23-132912](https://user-images.githubusercontent.com/8273519/159698217-bcbd3377-a546-4df3-b672-c77aee01710e.png)

**Comment by bnoordhuis** [comment]
It moved here: https://docs.libuv.org/en/v1.x/guide.html

**Comment by mihaiolteanu** [comment]
I understand that.
The about page still references the old location, it's all I'm sayin' :)

![Mar26-110947](https://user-images.githubusercontent.com/8273519/160234644-f1c95484-72cb-482c-938e-838440ae8b73.png)

**Comment by rickyrick2002** [comment]
> It moved here: https://docs.libuv.org/en/v1.x/guide.html

I won't know that this book is collected as the official doc till I read this issue. Thanks. 

A PR to `README.md` should be submit to inform newcomers.

**Comment by nikhilm** [comment]
I've fixed the About as well as the README to reflect the latest status of this repo.

I'm going to archive the repo. Thanks all!
